# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

global:
  domain: apps.ocp.example.com # Set this to the domain of your Openshift routes (or K8's services)
  # Configure any other global variables (e.g. openshift, persistentStorage) below

# something
jenkins:
  numAgents: 4 # Set this to the desired number of Jenkins Agents/Executors
  # Configure additional Jenkins variables as necessary

sonarqube:
  enabled: true
  # Configure additional Sonarqube variables as necessary

selenium:
  enabled: true
  # Configure additional Selenium variables as necessary
