# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium
    node: hub
  name: selenium-hub
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: 4444-tcp
      port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    deploymentconfig: selenium-hub

