# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl
global:
  openshift: true
  persistentStorage: true
  domain: apps.ocp.example.com
  sourceRepositoryUrl: "https://github.com/boozallen/sdp-helm-chart"
  sourceSecret: github

#domain: null
subdomain: jenkins
masterDockerContextDir: resources/jenkins-master
agentDockerContextDir: resources/jenkins-agent
numAgents: 4
#sourceRepositoryUrl: null
#sourceRepositoryBranch: null # defaults to master
#imageTag: null # defaults to .Chart.version
#sourceSecret: null
resources:
  master:
    limits:
      cpu: "1000m"
      memory: "4000Mi"
    requests:
      cpu: "1000m"
      memory: "4000Mi"
  agent:
    limits:
      cpu: "1000m"
      memory: "1500Mi"
    requests:
      cpu: "1000m"
      memory: "1500Mi"
dockerStorage: "100Gi"
dockerDaemonArgs: "--insecure-registry docker-registry.default.svc:5000"
