# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-credential-configuration
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
data:
    username: {{ randAlphaNum 10 | b64enc | quote }}
    password: {{ randAlphaNum 10 | b64enc | quote }}
