# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

apiVersion: v1
kind: Template
metadata:
  name: tiller-roles
  annotations:
    description: "RBAC required for helm"
objects:

# lets tiller store release information in configmaps
- kind: Role
  apiVersion: v1
  metadata:
    name: tiller-manager
    namespace: ${TILLER_NAMESPACE}
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - "*"
    verbs:
    - "*"

- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: tiller-manager
    namespace: ${TILLER_NAMESPACE}
  roleRef:
    name: tiller-manager
    namespace: ${TILLER_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: ${TILLER_NAMESPACE}
  userNames:
  - system:serviceaccount:${TILLER_NAMESPACE}:tiller

parameters:
- name: TILLER_NAMESPACE
  description: "the tiller namespace"
