# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

kind: List
apiVersion: v1
metadata:
  name: credential-secrets
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: jenkins-credential-configuration
    namespace: {{ .Release.Namespace }}
    labels:
      app: jenkins
  data:
    credential-configuration: |
      {{ include "jenkins.createCredentials" . | b64enc }}
