# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: "jenkins_edit"
  namespace: {{ .Release.Namespace }}
groupNames:
subjects:
- kind: ServiceAccount
  name: jenkins
roleRef:
  name: edit
