# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

kind: Service
apiVersion: v1
metadata:
  name: jenkins-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
spec:
  ports:
  - name: web
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 0
  selector:
    app: jenkins
    deploymentconfig: jenkins-master
